3_AUGUST_NUMPY_UNIVERSAL FUNCTION 


In [1]:
# ufuncs -- universal functions

# vectorization -- process of converting iterative statements into vector-based operations 

# without universal function
# x = [1,2,3,4]
# y = [4,5,6,7]
# z = []

# for i,j in zip(x,y):
#     z.append(i+j)
#     print(z)


# with universal function 
import numpy as np
x = [1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)

[ 5  7  9 11]


In [2]:
# you can create your own universal function also by using -- frompyfunc() method 

import numpy as np
def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [ ]:
# ufuncs operation -- add(), subtract(), multiply(), divide(),power(), mod(), REMAINDER(),DIVMOD()

import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
new_arr = np.add(arr1,arr2)
print(new_arr)

arr1 = np.array([5,6,7,8])
arr2 = np.array([1,2,3,4])
new_arr = np.subtract(arr1,arr2)
print(new_arr)

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
new_arr = np.multiply(arr1,arr2)
print(new_arr)

arr1 = np.array([10,20,30,40])
arr2 = np.array([5,6,7,8])
new_arr = np.divide(arr1,arr2)
print(new_arr)


[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[2.         3.33333333 4.28571429 5.        ]


In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,5,6,8,2,33])
new_arr = np.power(arr1,arr2)
print(new_arr)


[      1000    3200000  729000000 -520093696       2500          0]


In [5]:
# np.mod(arr1,arr2)
# np.remainder(arr1,arr2)
# newarr = divmod(arr1,arr2)

In [6]:
# exponential 

import numpy as np
x = np.array([1,2,3])
exp_arr = np.exp(x)
print(exp_arr)


[ 2.71828183  7.3890561  20.08553692]


In [7]:
import numpy as np 
v = np.exp([1,2])
r = np.log(v)
print(r)

[1. 2.]


In [8]:
# square root

import numpy as np 
v = np.array([1,4,9,16,25])
r = np.sqrt(v)
print(r)

[1. 2. 3. 4. 5.]


In [9]:
# maxium and minimum

import numpy as np
a = np.array([2,8,125])
b = np.array([3,3,15])
print(np.maximum(a,b))


a = np.array([2,8,125])
b = np.array([3,3,15])
print(np.minimum(a,b))


[  3   8 125]
[ 2  3 15]


4_ AUGUST_NUMPY UNIVERSAL FUNCTION


In [ ]:
# sum 

import numpy as np
arr1 = np.array([2,8,125])
arr2 = np.array([3,3,15])
new_arr = np.sum([arr1,arr2])
print(new_arr)

156


In [ ]:
# summation over axis -- sum([a,b],axis= 1)

import numpy as np
arr1 = np.array([2,8,125])
arr2 = np.array([3,3,15])
new_arr = np.sum([arr1,arr2],axis=1)
print(new_arr)


[135  21]


In [ ]:
# cumulative summation -- cumsum()

import numpy as np
arr1 = np.array([2,8,125])
arr2 = np.array([3,3,15])
new_arr = np.cumsum([arr1,arr2])
print(new_arr)




[  2  10 135 138 141 156]


In [ ]:
# PRODUCT OF ARRAYS

import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
x = np.prod([arr1,arr2])
print(x)

40320


In [8]:
# SUMATION PRODUCT
 
import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
x = np.prod([arr1,arr2],axis=1)
print(x)


# CUMULATIVE PRODUCT -- CUMPROD()

import numpy as np
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
x = np.cumprod([arr1,arr2])
print(x)

[  24 1680]
[    1     2     6    24   120   720  5040 40320]


In [9]:
# DISCREATE DIFFERENCE 
# SUBTRACTION BETWEEN ELEMENTS 
# [1,2,3,4] = [1-0,2-1,3-2,4-3] = [1,1,1,1]

import numpy as np
arr = np.array([10,45,43,23,60])
newarr = np.diff(arr)
print(newarr)

[ 35  -2 -20  37]


In [1]:
# JOIN NUMPY ARRAYS

# putting the content of 2 or more arrays in a single array thru concatenate function concatenate()

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# class task -- join two 2-D arrays along axis 

import numpy as np
arr1 = np.array([[2,3,4],[5,6,7]])
arr2 = np.array([[9,7,6],[45,34,54]])
newarr = np.concatenate((arr1,arr2),axis=1)
print(newarr)




[[ 2  3  4  9  7  6]
 [ 5  6  7 45 34 54]]


In [ ]:
# join array using stack function -- it is same as concatenate the only difference is that stacking is done along new axis 

# stack , hstack(), vstack(), dsatck().

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)



[[1 4]
 [2 5]
 [3 6]]


In [16]:
# hstack()

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

# vstack()

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

# dstack()

import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# array split -- array splitting means breaking the array into multiple array



# array_split() method

import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = np.array_split(arr,3)  # here 3 denotes, how many time we want array splitting - 3 times or 4 times 
print(new_arr)



[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# class task -- split the 2-d array into 3 2D array 

import numpy as np
a = np.array([[23,45,67],[87,65,43],[34,56,78]])
new = np.array_split(a,3)
print(new)


[array([[23, 45, 67]]), array([[87, 65, 43]]), array([[34, 56, 78]])]


In [42]:
# class task -- split the 2D array containing 3 element each into 4 2D array

import numpy as np
a = np.array([[23,34,45],[45,67,10],[1,2,3],[4,5,6]])
new_arr = np.array_split(a,4)
print(new_arr)

[array([[23, 34, 45]]), array([[45, 67, 10]]), array([[1, 2, 3]]), array([[4, 5, 6]])]


In [50]:
# 3d array

import numpy as np
a = np.array([[[1,2,3],[4,5,6]],
             [[9,8,7],[6,5,4]]])
new_arr = np.array_split(a,2)
print(new_arr)


[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[9, 8, 7],
        [6, 5, 4]]])]


In [ ]:

# hsplit(),vsplit(),dsplit()

In [53]:

# Search array 
# we can search an array for a certain value and return the indexes that get a match, to search an array we use where() function 


import numpy as np 
arr = np.array([1,2,3,4,5,4,4,])
x = np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [ ]:
# class task -- find the indexes where the values are odd

import numpy as np 
arr = np.array([10,14,93,41,8,7])
x = np.where(arr%2 !=0)
print(x)

# for even 
import numpy as np 
arr = np.array([10,14,93,41,8,7])
x = np.where(arr%2 ==0)
print(x)


(array([2, 3, 5], dtype=int64),)
(array([0, 1, 4], dtype=int64),)


In [63]:
# search sorted()

import numpy as np
arr = np.array([6,7,8,9])
v = np.searchsorted(arr,7)
print(v)

1


In [68]:
# SORTING 
# it creates a copy of the array leaving the original array unchanged 
# sort()-- sort the array 

import numpy as np
arr = np.array([3,7,5,4,6,2,0,1])
a = np.array(['cherry','apple','mango','banana'])
b = np.array([[3,2,1],[5,6,4]])
print(np.sort(arr))
print(np.sort(a))
print(np.sort(b))



[0 1 2 3 4 5 6 7]
['apple' 'banana' 'cherry' 'mango']
[[1 2 3]
 [4 5 6]]
