ARRAY JOINING (10 EXERCISE)

In [ ]:
# 1. Create two 1D arrays and join them

import numpy as np

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

a = np.concatenate((arr1, arr2))
print(a)


[2 3 4 5 6 7]


In [ ]:

# 2.	2. Join three arrays into one.

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])
arr3 = np.array([8,9,10])

c = np.concatenate((arr1, arr2, arr3))
print(c)

[ 2  3  4  5  6  7  8  9 10]


In [3]:
# 3.	3. Join two 2D arrays row-wise (axis=0).

arr1 = np.array([[2,3,4],[5,6,7]])
arr2 = np.array([[8,9,10],[11,12,13]])

b = np.concatenate((arr1, arr2), axis=0)
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [4]:
# 4.	4. Join two 2D arrays column-wise (axis=1).
arr1 = np.array([[2,3,4],[5,6,7]])
arr2 = np.array([[8,9,10],[11,12,13]])

d = np.concatenate((arr1, arr2), axis=1)
print(d)

[[ 2  3  4  8  9 10]
 [ 5  6  7 11 12 13]]


In [5]:
# 5.	5. Use np.stack() on two arrays.

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

s = np.stack((arr1, arr2))
print(s)

[[2 3 4]
 [5 6 7]]


In [6]:
# 6.	6. Use np.hstack() on two arrays

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

s = np.hstack((arr1, arr2))
print(s)

[2 3 4 5 6 7]


In [7]:
# 7.	7. Use np.vstack() on two arrays.

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

s = np.vstack((arr1, arr2))
print(s)

[[2 3 4]
 [5 6 7]]


In [8]:
# 8.	8. Join arrays using np.concatenate().

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

c = np.concatenate((arr1, arr2))
print(c)

[2 3 4 5 6 7]


In [10]:
# 9.	9. Predict the output before running concatenate.

arr1 = np.array([2,3,4])
arr2 = np.array([5,6,7])

print("the arr1 before concatenate:", arr1)
print("the arr2 before concatenate:", arr2)

c = np.concatenate((arr1, arr2))
print("the concatenated array:", c)

the arr1 before concatenate: [2 3 4]
the arr2 before concatenate: [5 6 7]
the concatenated array: [2 3 4 5 6 7]


In [11]:
# 10.	10. Create two student score arrays and merge them.

marks1= np.array([60,75,80,90,55])
marks2=np.array([65,70,85,88,60])

merged_marks = np.concatenate((marks1, marks2))
print("Merged student scores:", merged_marks)

Merged student scores: [60 75 80 90 55 65 70 85 88 60]


ARRAY SPLITTING (10 EXERCISE)

In [13]:
arr1 = np.array([2,3,4])


S = np.array_split(arr1, 2)
print(S)

[array([2, 3]), array([4])]


In [ ]:
# 12.	2. Split a 1D array into 4 parts.

arr1 = np.array([2,3,4,5,6,7,8])

s = np.array_split(arr1, 4)
print(s)

[array([2, 3]), array([4, 5]), array([6, 7]), array([8])]


In [15]:
# 13.	3. Split a 2D array row-wise

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
s = np.array_split(arr, 4, axis=0)
print(s)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [16]:
# 14.	4. Split a 2D array column-wise

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
s = np.array_split(arr, 4, axis=1)
print(s)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]]), array([], shape=(4, 0), dtype=int32)]


In [22]:
# 15.	5. Use np.array_split() on an uneven array

a = np.array([1,2,3,4,5,6,7])
s = np.array_split(a, 3)
print(s)





[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
# 16.	6. Explain difference between split and array_split

# np.split() --it splits the array into equal parts 

# np.array_split() --it splits the array into equal or unequal parts


#split()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
s = np.split(arr, 3)
print(s)


# array_split()
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
s = np.array_split(arr, 3)
print(s)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [30]:
# 17.	7. Split into 3 sections and print each.

import numpy as np
arr = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
results = np.split(arr, 3)

print(results[0])
print(results[1])
print(results[2])

# for part in results:
#     print(part)

[1 2 3]
[4 5 6]
[7 8 9]


In [29]:
# 18.	8. Access the second split.

import numpy as np
arr = np.array([1,2, 3, 4, 5, 6, 7, 8, 9])
results = np.split(arr, 3)

print(results[1])

[4 5 6]


In [3]:
# 19.	9. Split a matrix into individual rows.
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = np.split(matrix,3,axis=0)

print(rows)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [5]:
# 20.	10. Create a dataset and split into batches.

dataset = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
batches = np.array_split(dataset, 5)
print("The first batch is:", batches[0])
print("The second batch is:", batches[1])
print("The third batch is:", batches[2])
print("The fourth batch is:", batches[3])
print("The fifth batch is:", batches[4])

The first batch is: [10 20]
The second batch is: [30 40]
The third batch is: [50 60]
The fourth batch is: [70 80]
The fifth batch is: [ 90 100]


ARRAY SEARCHING

In [ ]:
# 21.	1. Find index of value 5 using where().
